### ISSUE TITLE
Autoloading and XmlLens loading fails

### ISSUE THREAD

**Issue by olifre** [voxpupuli/puppet-xmlfile#21]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.25.0
- Distribution: OSS Puppet Agent from Puppetlabs repositories on Debian 11 / Bullseye
- Module version: master

## How to reproduce (e.g Puppet code you use)
```puppet
$_pam_mount_config = '/etc/security/pam_mount.conf.xml'
xmlfile { $_pam_mount_config:
  ensure => present,
}
```

## What are you seeing
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/xmlfile: no such file to load -- puppet_x/vox_pupuli/xmlfile/lens (file: /etc/puppetlabs/code/environments/production/modules/profile/manifests/pam_mount_sshfs.pp, line: 41, column: 1) on node mynode.example.com
```
Restarting the server or running `puppet agent -t` on the server did not help. Then, I executed:
```
puppet generate types --environment production --force
```
(is this needed?). Afterwards, I get:
```
Error: Could not set 'present' on ensure: uninitialized constant XmlLens (file: /etc/puppetlabs/code/environments/production/modules/profile/manifests/pam_mount_sshfs.pp, line: 41)
Error: Could not set 'present' on ensure: uninitialized constant XmlLens (file: /etc/puppetlabs/code/environments/production/modules/profile/manifests/pam_mount_sshfs.pp, line: 41)
Wrapped exception:
uninitialized constant XmlLens
Error: /Stage[main]/Profile::Pam_mount_sshfs/Xmlfile[/etc/security/pam_mount.conf.xml]/ensure: change from 'absent' to 'present' failed: Could not set 'present' on ensure: uninitialized constant XmlLens (file: /etc/puppetlabs/code/environments/production/modules/profile/manifests/pam_mount_sshfs.pp, line: 41)
```

## What behaviour did you expect instead
Things to work...

**Comment by wolfaba** [comment]
Is maybe the problem, that in puppet_x/vox_pupuli/xmlfile/lens.rb there is require 'rexml/document' which is ruby unable to load/find? Maybe I say stupid thing, but there is some require error in the puppet log

```
org/jruby/RubyKernel.java:974:in `require'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83:in `require'
/etc/puppetlabs/code/environments/fisheye/modules/xmlfile/lib/puppet/type/xmlfile.rb:5:in `<main>'
org/jruby/RubyKernel.java:1009:in `load'
```

(sorry, I'm no puppet nor ruby professional).

Thank you for hint or fix.

**Comment by olifre** [comment]
I think that relates to the code not finding `lens.rb` itself, since the full message is:;
```
2021-11-02T20:15:28.076+01:00 ERROR [qtp1857304633-34] [puppetserver] Puppet Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/xmlfile: no such file to load -- puppet_x/vox_pupuli/xmlfile/lens (file: /etc/puppetlabs/code/environments/production/modules/profile/manifests/pam_mount_sshfs.pp, line: 72, column: 1) on node mynode.example.com
```
i.e. the main error is:
```
no such file to load -- puppet_x/vox_pupuli/xmlfile/lens
```

Indeed, trying:
```
/opt/puppetlabs/puppet/bin/ruby
require 'rexml/document'
<Ctrl+D>
```
yields no error message, i.e. `rexml` seems to be found just fine.

**Comment by wolfaba** [comment]
OK, I'm neither ruby nor puppet expert. But you are right. I have tried now run your test command in strace and puppet does not search lens.rb in /opt/puppetlabs/puppet/cache/lib. The lens.rb is saved in `/opt/puppetlabs/puppet/cache/lib/puppet_x/vox_pupuli/xmlfile/lens.rb`

```
12644 read(0, "require 'puppet_x/vox_pupuli/xmlfile/lens'\n", 8192) = 43
12644 read(0, "", 8192)                 = 0
12644 open("/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/puppet_x/vox_pupuli/xmlfile/lens.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
12644 open("/opt/puppetlabs/puppet/lib/ruby/site_ruby/2.5.0/puppet_x/vox_pupuli/xmlfile/lens.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
12644 open("/opt/puppetlabs/puppet/lib/ruby/site_ruby/2.5.0/x86_64-linux/puppet_x/vox_pupuli/xmlfile/lens.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
12644 open("/opt/puppetlabs/puppet/lib/ruby/site_ruby/puppet_x/vox_pupuli/xmlfile/lens.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
12644 open("/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/2.5.0/puppet_x/vox_pupuli/xmlfile/lens.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
12644 open("/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/2.5.0/x86_64-linux/puppet_x/vox_pupuli/xmlfile/lens.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
12644 open("/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet_x/vox_pupuli/xmlfile/lens.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
12644 open("/opt/puppetlabs/puppet/lib/ruby/2.5.0/puppet_x/vox_pupuli/xmlfile/lens.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
12644 open("/opt/puppetlabs/puppet/lib/ruby/2.5.0/x86_64-linux/puppet_x/vox_pupuli/xmlfile/lens.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
12644 open("/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/puppet_x/vox_pupuli/xmlfile/lens.so", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
12644 open("/opt/puppetlabs/puppet/lib/ruby/site_ruby/2.5.0/puppet_x/vox_pupuli/xmlfile/lens.so", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
12644 open("/opt/puppetlabs/puppet/lib/ruby/site_ruby/2.5.0/x86_64-linux/puppet_x/vox_pupuli/xmlfile/lens.so", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
12644 open("/opt/puppetlabs/puppet/lib/ruby/site_ruby/puppet_x/vox_pupuli/xmlfile/lens.so", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
12644 open("/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/2.5.0/puppet_x/vox_pupuli/xmlfile/lens.so", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
12644 open("/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/2.5.0/x86_64-linux/puppet_x/vox_pupuli/xmlfile/lens.so", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
12644 open("/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet_x/vox_pupuli/xmlfile/lens.so", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
12644 open("/opt/puppetlabs/puppet/lib/ruby/2.5.0/puppet_x/vox_pupuli/xmlfile/lens.so", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
12644 open("/opt/puppetlabs/puppet/lib/ruby/2.5.0/x86_64-linux/puppet_x/vox_pupuli/xmlfile/lens.so", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

If you try enter full pfad, `require '/opt/puppetlabs/puppet/cache/lib/puppet_x/vox_pupuli/xmlfile/lens'`, then it reports no error. So from any reason, the lens.rb is stored to `cache` subfolder, but ruby does not search there.

Any idea?

**Comment by wolfaba** [comment]
Hmm, on puppet server in `/etc/puppetlabs/code/environments/fisheye/modules/xmlfile/lib/puppet/type/xmlfile.rb` I have changed `require 'puppet_x/vox_pupuli/xmlfile/lens'` to `require_relative '../../puppet_x/vox_pupuli/xmlfile/lens'` and now I get the same error `uninitialized constant XmlLens` as you.

**Comment by wolfaba** [comment]
hmmm, in tag v0.4.0, there is a code `process = XmlLens.new(xml_content, resource[:changes], resource[:onlyif])` on the line 207 of `lib/puppet/type/xmlfile.rb`. In the file `lib/puppet/provider/xmlfile/lens.rb` there is really class definition `class XmlLens` on the line 5.

in the tag v1.0.0 and master there is still the line 211 in the file `lib/puppet/type/xmlfile.rb` with the code `process = XmlLens.new(xml_content, resource[:changes], resource[:onlyif])`. But in the file `lib/puppet_x/vox_pupuli/xmlfile/lens.rb` there is no `class XmlLens`, instead, there is `class Lens` on the line 8.

The `class Lens` is included in 
```
module PuppetX
  module VoxPupuli
    module Xmlfile
```

so I have tried to replace `process = XmlLens.new(xml_content, resource[:changes], resource[:onlyif])` with `process = PuppetX::VoxPupuli::Xmlfile::Lens.new(xml_content, resource[:changes], resource[:onlyif])`

and ... success!!! Now the XML file has been processed.

The original content has been deleted, but this is probably my incorrect configuration.

**Comment by unkinected** [comment]
It looks like this was fixed, but the changes have not been pushed back to the puppet forge? The latest version on the forge is 1.0.0 from June 2021. These changes were merged in Nov 2021. Can you please push the latest to the forge?
